name: flutter_newprojct
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^16.2.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.1.0
  intl: ^0.20.2
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - asset/icon/
    - asset/image/

